### ISSUE TITLE
Game Crashes whenever it tries to generate a chunck with a Round Cave (edit: or caves in general, or so it seems)

### ISSUE THREAD

**Issue by Byomakuta** [Someone-Else-Was-Taken/BetterEndForge-Reforked#44]
Good afternoon

i reach upon this way to address an issue i ran recently while playing, which is game crashing whenever render distance tries to generate a round cave (edit: also happened with tunnel caves so seems like caves in general), at least based on the features tab of the chash report, plus some indications of the issue rooting from the EndCave Feature provided by apparently the "mod.beethoven92.betterendforge.common.world.feature.caves.EndCaveFeature.setBiome" (just in case, i did replaced the old mod with the current updated one before)

if there is a way to fix or pass by this issue, or at least to disable the round_cave (cave overall) generation feature, it would also be appreciated, even if may be considered a short term solution

sorry for inconvenience and have a good day orz  

here below, i share the log detailed walkthrough, hope can be helpful o/
```A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.world.biome.BiomeContainer.setBiome(SourceFile:539) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:betterendforge.mixins.json:BiomeContainerMixin,pl:mixin:APP:helium.mixins.json:chunk.MixinBiomeArray,pl:mixin:APP:byg.mixins.json:access.BiomeContainerAccess,pl:mixin:A}
	at mod.beethoven92.betterendforge.common.world.feature.caves.EndCaveFeature.setBiome(EndCaveFeature.java:191) ~[?:1.16.5-2.5] {re:classloading}
	at mod.beethoven92.betterendforge.common.world.feature.caves.EndCaveFeature.lambda$setBiomes$4(EndCaveFeature.java:183) ~[?:1.16.5-2.5] {re:classloading}
	at mod.beethoven92.betterendforge.common.world.feature.caves.EndCaveFeature$$Lambda$49868/1316062631.accept(Unknown Source) ~[?:?] {}
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:1.8.0_51] {}
	at mod.beethoven92.betterendforge.common.world.feature.caves.EndCaveFeature.setBiomes(EndCaveFeature.java:183) ~[?:1.16.5-2.5] {re:classloading}
	at mod.beethoven92.betterendforge.common.world.feature.caves.EndCaveFeature.generate(EndCaveFeature.java:79) ~[?:1.16.5-2.5] {re:classloading}
	at mod.beethoven92.betterendforge.common.world.feature.caves.EndCaveFeature.func_241855_a(EndCaveFeature.java:32) ~[?:1.16.5-2.5] {re:classloading}
	at net.minecraft.world.gen.feature.ConfiguredFeature.func_242765_a(SourceFile:55) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:blue_skies.mixins.json:ConfiguredFeatureMixin,pl:mixin:A}
	at net.minecraft.world.gen.feature.DecoratedFeature.func_242772_a(SourceFile:23) ~[?:?] {re:classloading}
	at net.minecraft.world.gen.feature.DecoratedFeature$$Lambda$46566/560526424.accept(Unknown Source) ~[?:?] {}
	at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:419) ~[?:1.8.0_51] {}
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580) ~[?:1.8.0_51] {}
	at net.minecraft.world.gen.feature.DecoratedFeature.func_241855_a(SourceFile:22) ~[?:?] {re:classloading}
	at net.minecraft.world.gen.feature.DecoratedFeature.func_241855_a(SourceFile:14) ~[?:?] {re:classloading}
	at net.minecraft.world.gen.feature.ConfiguredFeature.func_242765_a(SourceFile:55) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:blue_skies.mixins.json:ConfiguredFeatureMixin,pl:mixin:A}
-- Feature --
Details:
	Id: minecraft:decorated
	Config: < DecoratedFeatureConfig [betterendforge:round_cave | [minecraft:chance net.minecraft.world.gen.placement.ChanceConfig@396b78c4]] >
	Description: < DecoratedFeature [minecraft:decorated] >
Stacktrace:
	at net.minecraft.world.biome.Biome.func_242427_a(Biome.java:254) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins.environs.json:MixinBiome,pl:mixin:APP:byg.mixins.json:access.BiomeAccess,pl:mixin:APP:blue_skies.mixins.json:BiomeMixin,pl:mixin:A}


-- Generation --
Details:
	CenterX: -19
	CenterZ: -69
	Seed: 818435849964229003
	Biome: net.minecraft.world.biome.Biome@1b37da6b
Stacktrace:
	at net.minecraft.world.gen.ChunkGenerator.func_230351_a_(SourceFile:220) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:betterdungeons.mixins.json:ChunkGeneratorAccessor,pl:mixin:APP:betternether.mixins.json:ChunkGeneratorMixin,pl:mixin:APP:yungsapi.mixins.json:ChunkGeneratorAccessor,pl:mixin:APP:repurposed_structures.mixins.json:world.ChunkGeneratorAccessor,pl:mixin:APP:betterstrongholds.mixins.json:VanillaStrongholdSpawnMixin,pl:mixin:APP:betterstrongholds.mixins.json:ChunkGeneratorAccessor,pl:mixin:APP:cavebiomeapi.mixins.json:ChunkGeneratorMixin,pl:mixin:A}
	at net.minecraft.world.chunk.ChunkStatus.func_222605_b(ChunkStatus.java:77) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:sulfuric.mixins.json:chunk.MixinChunkStatus,pl:mixin:APP:byg.mixins.json:common.world.ChunkStatusMixin,pl:mixin:A}
	at net.minecraft.world.chunk.ChunkStatus$$Lambda$2397/1948191643.doWork(Unknown Source) ~[?:?] {}
	at net.minecraft.world.chunk.ChunkStatus.md2b145a$lambda$injectLightmapSetup$1$4(ChunkStatus.java:551) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:sulfuric.mixins.json:chunk.MixinChunkStatus,pl:mixin:APP:byg.mixins.json:common.world.ChunkStatusMixin,pl:mixin:A}
	at net.minecraft.world.chunk.ChunkStatus$$Lambda$2398/1905806448.doWork(Unknown Source) ~[?:?] {}
	at net.minecraft.world.chunk.ChunkStatus.func_223198_a(ChunkStatus.java:198) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:sulfuric.mixins.json:chunk.MixinChunkStatus,pl:mixin:APP:byg.mixins.json:common.world.ChunkStatusMixin,pl:mixin:A}


-- Chunk to be generated --
Details:
	Location: -19,-69
	Position hash: -292057776147
	Generator: net.minecraft.world.gen.NoiseChunkGenerator@2d37f457
Stacktrace:
	at net.minecraft.world.server.ChunkManager.lambda$null$18(ChunkManager.java:524) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:sulfuric.mixins.json:world.MixinThreadedAnvilChunkStorage,pl:mixin:APP:performant.mixins.json:world.chunk.ChunkManagerMixin,pl:mixin:APP:performant.mixins.json:world.chunk.ChunkManagerUpdatePlayerPosMixin,pl:mixin:APP:performant.mixins.json:world.chunk.ChunkManagerChunksAccessor,pl:mixin:A}
	at net.minecraft.world.server.ChunkManager$$Lambda$46407/1070853797.apply(Unknown Source) ~[?:?] {}
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-4.0.26.jar:?] {re:classloading,re:classloading,re:classloading}
	at net.minecraft.world.server.ChunkManager.lambda$scheduleChunkGeneration$20(ChunkManager.java:522) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:sulfuric.mixins.json:world.MixinThreadedAnvilChunkStorage,pl:mixin:APP:performant.mixins.json:world.chunk.ChunkManagerMixin,pl:mixin:APP:performant.mixins.json:world.chunk.ChunkManagerUpdatePlayerPosMixin,pl:mixin:APP:performant.mixins.json:world.chunk.ChunkManagerChunksAccessor,pl:mixin:A}
	at net.minecraft.world.server.ChunkManager$$Lambda$46404/1255246029.apply(Unknown Source) ~[?:?] {}
	at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:952) ~[?:1.8.0_51] {}
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:926) ~[?:1.8.0_51] {}
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442) ~[?:1.8.0_51] {}
	at net.minecraft.world.chunk.ChunkTaskPriorityQueueSorter.func_219083_b(SourceFile:58) ~[?:?] {re:classloading}
	at net.minecraft.world.chunk.ChunkTaskPriorityQueueSorter$$Lambda$46156/1378445675.run(Unknown Source) ~[?:?] {}
	at net.minecraft.util.concurrent.DelegatedTaskExecutor.func_213148_e(SourceFile:94) ~[?:?] {re:classloading}


-- Affected level --
Details:
	All players: 1 total; [ServerPlayerEntity['Byomi'/158, l='ServerLevel[Nova]', x=-144.10, y=71.23, z=-1154.67]]
	Chunk stats: ServerChunkCache: 1520
	Level dimension: minecraft:the_end
	Derived: true
	Level spawn location: World: (230,68,223), Chunk: (at 6,4,15 in 14,13; contains blocks 224,0,208 to 239,255,223), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 3810994 game time, 4608752 day time
	Level name: Nova
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: true
	Level weather: Rain time: 154840 (now: false), thunder time: 34579 (now: false)
	Known server brands: forge
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:854) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:betterendforge.mixins.json:MinecraftServerMixin,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:betterendforge.mixins.json:MinecraftServerMixin,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:A}
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:78) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) [?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:betterendforge.mixins.json:MinecraftServerMixin,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) [?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:betterendforge.mixins.json:MinecraftServerMixin,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:A}
	at net.minecraft.server.MinecraftServer$$Lambda$45819/1636286379.run(Unknown Source) [?:?] {}
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51] {}```

**Comment by mr-poyo** [comment]
I'm also getting this crash

**Comment by MagmaSlime123** [comment]
This mod is dead. Don't bother opening issues here.
