### ISSUE TITLE
Crash whenever you're generating caves in the end.

### ISSUE THREAD

**Issue by PeopleMcNugget** [Someone-Else-Was-Taken/BetterEndForge-Reforked#50]
I'm getting a persistent crash when the game is trying to load the End Cave structures from this mod in. I've noticed people having similar issues to this but it's a pretty big problem, sometimes the end will load then crash two or so minutes in, and sometimes I won't even be able to load in at all, and it gives me the same exact error.

---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 3/22/22 1:11 PM
Description: Feature placement

java.lang.NullPointerException: Feature placement
	at net.minecraft.world.biome.BiomeContainer.setBiome(SourceFile:539) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:betterendforge.mixins.json:BiomeContainerMixin,pl:mixin:APP:helium.mixins.json:chunk.MixinBiomeArray,pl:mixin:A}
	at mod.beethoven92.betterendforge.common.world.feature.caves.EndCaveFeature.setBiome(EndCaveFeature.java:191) ~[?:1.16.5-2.5] {re:classloading}
	at mod.beethoven92.betterendforge.common.world.feature.caves.TunelCaveFeature.lambda$generate$2(TunelCaveFeature.java:156) ~[?:1.16.5-2.5] {re:classloading}
	at mod.beethoven92.betterendforge.common.world.feature.caves.TunelCaveFeature$$Lambda$30386/240855041.accept(Unknown Source) ~[?:?] {}
	at java.util.concurrent.ConcurrentHashMap$KeySetView.forEach(ConcurrentHashMap.java:4649) ~[?:1.8.0_51] {}
	at java.util.Collections$SetFromMap.forEach(Collections.java:5476) ~[?:1.8.0_51] {}
	at mod.beethoven92.betterendforge.common.world.feature.caves.TunelCaveFeature.generate(TunelCaveFeature.java:130) ~[?:1.16.5-2.5] {re:classloading}
	at mod.beethoven92.betterendforge.common.world.feature.caves.TunelCaveFeature.func_241855_a(TunelCaveFeature.java:29) ~[?:1.16.5-2.5] {re:classloading}
	at net.minecraft.world.gen.feature.ConfiguredFeature.func_242765_a(SourceFile:55) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:blue_skies.mixins.json:ConfiguredFeatureMixin,pl:mixin:A}
	at net.minecraft.world.gen.feature.DecoratedFeature.func_242772_a(SourceFile:23) ~[?:?] {re:classloading}
	at net.minecraft.world.gen.feature.DecoratedFeature$$Lambda$27793/539339170.accept(Unknown Source) ~[?:?] {}
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) ~[?:1.8.0_51] {}
	at java.util.stream.IntPipeline$4$1.accept(IntPipeline.java:250) ~[?:1.8.0_51] {}
	at java.util.stream.Streams$RangeIntSpliterator.forEachRemaining(Streams.java:110) ~[?:1.8.0_51] {}
	at java.util.Spliterator$OfInt.forEachRemaining(Spliterator.java:693) ~[?:1.8.0_51] {}
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512) ~[?:1.8.0_51] {}
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502) ~[?:1.8.0_51] {}
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) ~[?:1.8.0_51] {}
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) ~[?:1.8.0_51] {}
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_51] {}
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418) ~[?:1.8.0_51] {}
	at net.minecraft.world.gen.feature.DecoratedFeature.func_241855_a(SourceFile:22) ~[?:?] {re:classloading}
	at net.minecraft.world.gen.feature.DecoratedFeature.func_241855_a(SourceFile:14) ~[?:?] {re:classloading}
	at net.minecraft.world.gen.feature.ConfiguredFeature.func_242765_a(SourceFile:55) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:blue_skies.mixins.json:ConfiguredFeatureMixin,pl:mixin:A}
	at net.minecraft.world.biome.Biome.func_242427_a(Biome.java:254) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:blue_skies.mixins.json:BiomeMixin,pl:mixin:APP:blame.mixins.json:BiomeMixin,pl:mixin:APP:terraincognita.mixins.json:client.BiomeMixin,pl:mixin:APP:fabric-biome-api.mixins.json:modification.BiomeAccessor,pl:mixin:A}
	at net.minecraft.world.gen.ChunkGenerator.func_230351_a_(SourceFile:220) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:betternether.mixins.json:ChunkGeneratorMixin,pl:mixin:APP:yungsapi.mixins.json:ChunkGeneratorAccessor,pl:mixin:APP:repurposed_structures.mixins.json:world.ChunkGeneratorAccessor,pl:mixin:APP:cavebiomeapi.mixins.json:ChunkGeneratorMixin,pl:mixin:A}
	at net.minecraft.world.chunk.ChunkStatus.func_222605_b(ChunkStatus.java:77) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:bettercaves.mixins.json:ChunkStatusMixin,pl:mixin:APP:sulfuric.mixins.json:chunk.MixinChunkStatus,pl:mixin:A}
	at net.minecraft.world.chunk.ChunkStatus$$Lambda$2368/734906604.doWork(Unknown Source) ~[?:?] {}
	at net.minecraft.world.chunk.ChunkStatus.md9a1e07$lambda$injectLightmapSetup$1$4(ChunkStatus.java:1051) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:bettercaves.mixins.json:ChunkStatusMixin,pl:mixin:APP:sulfuric.mixins.json:chunk.MixinChunkStatus,pl:mixin:A}
	at net.minecraft.world.chunk.ChunkStatus$$Lambda$2369/2132824865.doWork(Unknown Source) ~[?:?] {}
	at net.minecraft.world.chunk.ChunkStatus.func_223198_a(ChunkStatus.java:198) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:bettercaves.mixins.json:ChunkStatusMixin,pl:mixin:APP:sulfuric.mixins.json:chunk.MixinChunkStatus,pl:mixin:A}
	at net.minecraft.world.server.ChunkManager.lambda$null$18(ChunkManager.java:524) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:sulfuric.mixins.json:world.MixinThreadedAnvilChunkStorage,pl:mixin:APP:kryptonreforged.mixins.json:network.shared.flushconsolidation.ThreadedAnvilChunkStorageMixin,pl:mixin:A}
	at net.minecraft.world.server.ChunkManager$$Lambda$27642/1744787135.apply(Unknown Source) ~[?:?] {}
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-4.0.26.jar:?] {re:classloading,re:classloading}
	at net.minecraft.world.server.ChunkManager.lambda$scheduleChunkGeneration$20(ChunkManager.java:522) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:sulfuric.mixins.json:world.MixinThreadedAnvilChunkStorage,pl:mixin:APP:kryptonreforged.mixins.json:network.shared.flushconsolidation.ThreadedAnvilChunkStorageMixin,pl:mixin:A}
	at net.minecraft.world.server.ChunkManager$$Lambda$27627/1384163891.apply(Unknown Source) ~[?:?] {}
	at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:952) ~[?:1.8.0_51] {}
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:926) ~[?:1.8.0_51] {}
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442) ~[?:1.8.0_51] {}
	at net.minecraft.world.chunk.ChunkTaskPriorityQueueSorter.func_219083_b(SourceFile:58) ~[?:?] {re:classloading}
	at net.minecraft.world.chunk.ChunkTaskPriorityQueueSorter$$Lambda$27640/1779350088.run(Unknown Source) ~[?:?] {}
	at net.minecraft.util.concurrent.DelegatedTaskExecutor.func_213148_e(SourceFile:94) ~[?:?] {re:classloading}
	at net.minecraft.util.concurrent.DelegatedTaskExecutor.func_213145_a(SourceFile:137) ~[?:?] {re:classloading}
	at net.minecraft.util.concurrent.DelegatedTaskExecutor.run(SourceFile:105) ~[?:?] {re:classloading}
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689) ~[?:1.8.0_51] {re:computing_frames}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) ~[?:1.8.0_51] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.world.biome.BiomeContainer.setBiome(SourceFile:539) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:betterendforge.mixins.json:BiomeContainerMixin,pl:mixin:APP:helium.mixins.json:chunk.MixinBiomeArray,pl:mixin:A}
	at mod.beethoven92.betterendforge.common.world.feature.caves.EndCaveFeature.setBiome(EndCaveFeature.java:191) ~[?:1.16.5-2.5] {re:classloading}
	at mod.beethoven92.betterendforge.common.world.feature.caves.TunelCaveFeature.lambda$generate$2(TunelCaveFeature.java:156) ~[?:1.16.5-2.5] {re:classloading}
	at mod.beethoven92.betterendforge.common.world.feature.caves.TunelCaveFeature$$Lambda$30386/240855041.accept(Unknown Source) ~[?:?] {}
	at java.util.concurrent.ConcurrentHashMap$KeySetView.forEach(ConcurrentHashMap.java:4649) ~[?:1.8.0_51] {}
	at java.util.Collections$SetFromMap.forEach(Collections.java:5476) ~[?:1.8.0_51] {}
	at mod.beethoven92.betterendforge.common.world.feature.caves.TunelCaveFeature.generate(TunelCaveFeature.java:130) ~[?:1.16.5-2.5] {re:classloading}
	at mod.beethoven92.betterendforge.common.world.feature.caves.TunelCaveFeature.func_241855_a(TunelCaveFeature.java:29) ~[?:1.16.5-2.5] {re:classloading}
	at net.minecraft.world.gen.feature.ConfiguredFeature.func_242765_a(SourceFile:55) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:blue_skies.mixins.json:ConfiguredFeatureMixin,pl:mixin:A}
	at net.minecraft.world.gen.feature.DecoratedFeature.func_242772_a(SourceFile:23) ~[?:?] {re:classloading}
	at net.minecraft.world.gen.feature.DecoratedFeature$$Lambda$27793/539339170.accept(Unknown Source) ~[?:?] {}
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) ~[?:1.8.0_51] {}
	at java.util.stream.IntPipeline$4$1.accept(IntPipeline.java:250) ~[?:1.8.0_51] {}
	at java.util.stream.Streams$RangeIntSpliterator.forEachRemaining(Streams.java:110) ~[?:1.8.0_51] {}
	at java.util.Spliterator$OfInt.forEachRemaining(Spliterator.java:693) ~[?:1.8.0_51] {}
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512) ~[?:1.8.0_51] {}
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502) ~[?:1.8.0_51] {}
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151) ~[?:1.8.0_51] {}
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174) ~[?:1.8.0_51] {}
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_51] {}
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418) ~[?:1.8.0_51] {}
	at net.minecraft.world.gen.feature.DecoratedFeature.func_241855_a(SourceFile:22) ~[?:?] {re:classloading}
	at net.minecraft.world.gen.feature.DecoratedFeature.func_241855_a(SourceFile:14) ~[?:?] {re:classloading}
	at net.minecraft.world.gen.feature.ConfiguredFeature.func_242765_a(SourceFile:55) ~[?:?] {re:mixin,re:classloading,pl:mixin:APP:blue_skies.mixins.json:ConfiguredFeatureMixin,pl:mixin:A}
-- Feature --
Details:
	Id: minecraft:decorated
	Config: < DecoratedFeatureConfig [betterendforge:tunel_cave | [minecraft:count net.minecraft.world.gen.feature.FeatureSpreadConfig@ceacb8c]] >
	Description: < DecoratedFeature [minecraft:decorated] >
Stacktrace:
	at net.minecraft.world.biome.Biome.func_242427_a(Biome.java:254) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:blue_skies.mixins.json:BiomeMixin,pl:mixin:APP:blame.mixins.json:BiomeMixin,pl:mixin:APP:terraincognita.mixins.json:client.BiomeMixin,pl:mixin:APP:fabric-biome-api.mixins.json:modification.BiomeAccessor,pl:mixin:A}

**Comment by MagmaSlime123** [comment]
This mod is dead. Don't bother opening issues here.
