### ISSUE TITLE
BetterEnd Forge 2.5 + Forge 36.2.34

### ISSUE THREAD

**Issue by georgio3333** [Someone-Else-Was-Taken/BetterEndForge-Reforked#51]
Hello,

I have this issue when i try to connect to test.prisonfun.com or another lobby with just BetterEnd Forge 2.5.

![image](https://user-images.githubusercontent.com/19244649/169712255-71728058-7167-4502-85f1-7f265ee1096f.png)

> [22May2022 21:10:12.033] [main/INFO] [cpw.mods.modlauncher.Launcher/MODLAUNCHER]: ModLauncher running: args [--username, georgio33, --version, MultiMC5, --gameDir, G:/MultiMC/instances/1.16.5 test mod/.minecraft, --assetsDir, G:/MultiMC/assets, --assetIndex, 1.16, --uuid, f47bd0d606c64b7ebda6381f1d20f68c, --accessToken, ????????, --userType, msa, --versionType, release, --launchTarget, fmlclient, --fml.forgeVersion, 36.2.34, --fml.mcVersion, 1.16.5, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20210115.111550, --width, 854, --height, 480]
[22May2022 21:10:12.036] [main/INFO] [cpw.mods.modlauncher.Launcher/MODLAUNCHER]: ModLauncher 8.1.3+8.1.3+main-8.1.x.c94d18ec starting: java version 16.0.1 by Oracle Corporation
[22May2022 21:10:12.264] [main/INFO] [net.minecraftforge.fml.loading.FixSSL/CORE]: Added Lets Encrypt root certificates as additional trust
[22May2022 21:10:12.308] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8.4 Source=file:/G:/MultiMC/libraries/org/spongepowered/mixin/0.8.4/mixin-0.8.4.jar Service=ModLauncher Env=CLIENT
[22May2022 21:10:13.658] [main/INFO] [cpw.mods.modlauncher.LaunchServiceHandler/MODLAUNCHER]: Launching target 'fmlclient' with arguments [--version, MultiMC5, --gameDir, G:\MultiMC\instances\1.16.5 test mod\.minecraft, --assetsDir, G:\MultiMC\assets, --uuid, f47bd0d606c64b7ebda6381f1d20f68c, --username, georgio33, --assetIndex, 1.16, --accessToken, ????????, --userType, msa, --versionType, release, --width, 854, --height, 480]
[22May2022 21:10:17.755] [Render thread/INFO] [com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService/]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[22May2022 21:10:18.224] [Render thread/INFO] [net.minecraft.client.Minecraft/]: Setting user: georgio33
[22May2022 21:10:18.310] [Render thread/INFO] [net.minecraft.client.Minecraft/]: Backend library: LWJGL version 3.2.2 build 10
[22May2022 21:10:18.853] [modloading-worker-2/INFO] [net.minecraftforge.common.ForgeMod/FORGEMOD]: Forge mod loading, version 36.2.34, for MC 1.16.5 with MCP 20210115.111550
[22May2022 21:10:18.855] [modloading-worker-2/INFO] [net.minecraftforge.common.MinecraftForge/FORGE]: MinecraftForge v36.2.34 Initialized
[22May2022 21:10:19.980] [Render thread/WARN] [net.minecraftforge.registries.ForgeRegistry/REGISTRIES]: Registry minecraft:worldgen/biome: The object minecraft:the_end has been registered twice for the same name minecraft:the_end.
[22May2022 21:10:19.980] [Render thread/WARN] [net.minecraftforge.registries.ForgeRegistry/REGISTRIES]: Registry minecraft:worldgen/biome: The object minecraft:end_barrens has been registered twice for the same name minecraft:end_barrens.
[22May2022 21:10:19.980] [Render thread/WARN] [net.minecraftforge.registries.ForgeRegistry/REGISTRIES]: Registry minecraft:worldgen/biome: The object minecraft:small_end_islands has been registered twice for the same name minecraft:small_end_islands.
[22May2022 21:10:19.980] [Render thread/WARN] [net.minecraftforge.registries.ForgeRegistry/REGISTRIES]: Registry minecraft:worldgen/biome: The object minecraft:end_midlands has been registered twice for the same name minecraft:end_midlands.
[22May2022 21:10:19.980] [Render thread/WARN] [net.minecraftforge.registries.ForgeRegistry/REGISTRIES]: Registry minecraft:worldgen/biome: The object minecraft:end_highlands has been registered twice for the same name minecraft:end_highlands.
[22May2022 21:10:19.997] [Render thread/ERROR] [net.minecraft.util.registry.SimpleRegistry/]: Adding duplicate value 'mod.beethoven92.betterendforge.common.init.ModStructurePieces$$Lambda$3798/0x000000080166e730@36813df0' to registry
[22May2022 21:10:19.997] [Render thread/ERROR] [net.minecraft.util.registry.SimpleRegistry/]: Adding duplicate value 'mod.beethoven92.betterendforge.common.init.ModStructurePieces$$Lambda$3799/0x000000080166ec30@3661f97f' to registry
[22May2022 21:10:19.997] [Render thread/ERROR] [net.minecraft.util.registry.SimpleRegistry/]: Adding duplicate value 'mod.beethoven92.betterendforge.common.init.ModStructurePieces$$Lambda$3800/0x000000080166f138@5f01a321' to registry
[22May2022 21:10:19.997] [Render thread/ERROR] [net.minecraft.util.registry.SimpleRegistry/]: Adding duplicate value 'mod.beethoven92.betterendforge.common.init.ModStructurePieces$$Lambda$3801/0x000000080166f640@7219c965' to registry
[22May2022 21:10:19.997] [Render thread/ERROR] [net.minecraft.util.registry.SimpleRegistry/]: Adding duplicate value 'mod.beethoven92.betterendforge.common.init.ModStructurePieces$$Lambda$3802/0x000000080166fb48@50430d14' to registry
[22May2022 21:10:19.997] [Render thread/ERROR] [net.minecraft.util.registry.SimpleRegistry/]: Adding duplicate value 'mod.beethoven92.betterendforge.common.init.ModStructurePieces$$Lambda$3803/0x000000080166fd60@516b48bf' to registry
[22May2022 21:10:20.719] [Render thread/INFO] [com.mojang.text2speech.NarratorWindows/]: Narrator library for x64 successfully loaded
[22May2022 21:10:20.794] [Render thread/INFO] [net.minecraft.resources.SimpleReloadableResourceManager/]: Reloading ResourceManager: Default, Mod Resources, Programmer Art
[22May2022 21:10:20.909] [Forge Version Check/INFO] [net.minecraftforge.fml.VersionChecker/]: [forge] Starting version check at https://files.minecraftforge.net/net/minecraftforge/forge/promotions_slim.json
[22May2022 21:10:22.471] [Forge Version Check/INFO] [net.minecraftforge.fml.VersionChecker/]: [forge] Found status: UP_TO_DATE Current: 36.2.34 Target: null
[22May2022 21:10:25.293] [Render thread/INFO] [net.minecraft.client.audio.SoundSystem/]: OpenAL initialized.
[22May2022 21:10:25.294] [Render thread/INFO] [net.minecraft.client.audio.SoundEngine/SOUNDS]: Sound engine started
[22May2022 21:10:25.676] [Render thread/INFO] [net.minecraft.client.renderer.texture.AtlasTexture/]: Created: 1024x1024x4 minecraft:textures/atlas/blocks.png-atlas
[22May2022 21:10:25.693] [Render thread/INFO] [net.minecraft.client.renderer.texture.AtlasTexture/]: Created: 256x128x4 minecraft:textures/atlas/signs.png-atlas
[22May2022 21:10:25.694] [Render thread/INFO] [net.minecraft.client.renderer.texture.AtlasTexture/]: Created: 512x512x4 minecraft:textures/atlas/banner_patterns.png-atlas
[22May2022 21:10:25.695] [Render thread/INFO] [net.minecraft.client.renderer.texture.AtlasTexture/]: Created: 512x512x4 minecraft:textures/atlas/shield_patterns.png-atlas
[22May2022 21:10:25.696] [Render thread/INFO] [net.minecraft.client.renderer.texture.AtlasTexture/]: Created: 256x256x4 minecraft:textures/atlas/chest.png-atlas
[22May2022 21:10:25.697] [Render thread/INFO] [net.minecraft.client.renderer.texture.AtlasTexture/]: Created: 512x256x4 minecraft:textures/atlas/beds.png-atlas
[22May2022 21:10:25.697] [Render thread/INFO] [net.minecraft.client.renderer.texture.AtlasTexture/]: Created: 512x256x4 minecraft:textures/atlas/shulker_boxes.png-atlas
[22May2022 21:10:26.450] [Render thread/INFO] [net.minecraft.client.renderer.texture.AtlasTexture/]: Created: 256x256x0 minecraft:textures/atlas/particles.png-atlas
[22May2022 21:10:26.453] [Render thread/INFO] [net.minecraft.client.renderer.texture.AtlasTexture/]: Created: 256x256x0 minecraft:textures/atlas/paintings.png-atlas
[22May2022 21:10:26.453] [Render thread/INFO] [net.minecraft.client.renderer.texture.AtlasTexture/]: Created: 128x128x0 minecraft:textures/atlas/mob_effects.png-atlas
[22May2022 21:10:33.084] [Render thread/INFO] [net.minecraft.client.gui.screen.ConnectingScreen/]: Connecting to 192.168.1.201, 25565
[22May2022 21:10:38.172] [Netty Client IO #2/INFO] [net.minecraftforge.fml.network.NetworkHooks/]: Connected to a vanilla server. Catching up missing behaviour.
[22May2022 21:10:38.281] [Netty Client IO #2/ERROR] [net.minecraft.util.registry.WorldSettingsImport/]: Error adding element: Unknown registry element mod.beethoven92.betterendforge.common.world.feature.SinglePlantFeature@1c04684f
[22May2022 21:10:38.461] [Render thread/FATAL] [net.minecraft.util.concurrent.ThreadTaskExecutor/]: Error executing task on Client
net.minecraft.util.ResourceLocationException: Non [a-z0-9/._-] character in path of location: legacy:fml|hs
	at net.minecraft.util.ResourceLocation.<init>(ResourceLocation.java:33) ~[?:?]
	at net.minecraft.util.ResourceLocation.<init>(ResourceLocation.java:38) ~[?:?]
	at net.minecraftforge.fml.network.FMLMCRegisterPacketHandler$ChannelList.bytesToResLocation(FMLMCRegisterPacketHandler.java:78) ~[forge:?]
	at net.minecraftforge.fml.network.FMLMCRegisterPacketHandler$ChannelList.updateFrom(FMLMCRegisterPacketHandler.java:49) ~[forge:?]
	at net.minecraftforge.fml.network.FMLMCRegisterPacketHandler.registerListener(FMLMCRegisterPacketHandler.java:92) ~[forge:?]
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.fml.network.NetworkInstance.dispatch(NetworkInstance.java:86) ~[forge:?]
	at net.minecraftforge.fml.network.NetworkHooks.lambda$onCustomPayload$1(NetworkHooks.java:91) ~[forge:?]
	at java.util.Optional.map(Optional.java:260) ~[?:?]
	at net.minecraftforge.fml.network.NetworkHooks.onCustomPayload(NetworkHooks.java:91) ~[forge:?]
	at net.minecraft.client.network.play.ClientPlayNetHandler.func_147240_a(ClientPlayNetHandler.java:1904) ~[?:?]
	at net.minecraft.network.play.server.SCustomPayloadPlayPacket.func_148833_a(SCustomPayloadPlayPacket.java:59) ~[?:?]
	at net.minecraft.network.play.server.SCustomPayloadPlayPacket.func_148833_a(SCustomPayloadPlayPacket.java:11) ~[?:?]
	at net.minecraft.network.PacketThreadUtil.func_225383_a(SourceFile:21) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) ~[?:?]
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213160_bf(SourceFile:103) ~[?:?]
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:948) ~[?:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) ~[?:?]
	at net.minecraft.client.main.Main.main(Main.java:184) ~[minecraft-1.16.5-client.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) ~[forge-1.16.5-36.2.34-launcher.jar:36.2]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.1.3.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.1.3.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.1.3.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.1.3.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.1.3.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:57) [ForgeWrapper-mmc3.jar:mmc3]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
[22May2022 21:10:38.632] [Render thread/INFO] [com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService/]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[22May2022 21:10:38.709] [Render thread/WARN] [net.minecraft.client.network.play.ClientPlayNetHandler/]: Incomplete server tags, disconnecting. Missing: {minecraft:item=[betterendforge:end_lotus_logs, betterendforge:lucernia_logs, betterendforge:hammers, betterendforge:furnaces, betterendforge:helix_tree_logs, betterendforge:tenanea_logs, betterendforge:pythadendron_logs, forge:barrels/wooden, betterendforge:jellyshroom_logs, betterendforge:dragon_tree_logs, betterendforge:umbrella_tree_logs, betterendforge:mossy_glowshroom_logs, betterendforge:lacugrove_logs], minecraft:block=[betterendforge:end_lotus_logs, betterendforge:lucernia_logs, betterendforge:helix_tree_logs, betterendforge:end_ground, betterendforge:tenanea_logs, betterendforge:gen_terrain, betterendforge:pythadendron_logs, forge:barrels/wooden, betterendforge:jellyshroom_logs, betterendforge:dragon_tree_logs, betterendforge:umbrella_tree_logs, betterendforge:mossy_glowshroom_logs, betterendforge:lacugrove_logs]}
[22May2022 21:10:43.993] [Render thread/INFO] [net.minecraft.client.Minecraft/]: Stopping!

>

**Comment by MagmaSlime123** [comment]
This mod is dead. Don't bother opening issues here.
